var recipes = [
  {
    recipesName: "Caprese Sandwich",
    recipesImg: "Caprese Sandwich.avif",
    disc: "Fresh Italian sandwich with mozzarella, tomato, and basil",
    prepTime: "10 min",
    cookTime: "5 min",
    servings: "2 people",
    stars: "4.5",
    reviews: "(189 reviews)",
    tag1: "Easy",
    tag2: "Italian",
    calories: "480 kcal",
    protein: "22g",
    carbohydrates: "48g",
    fat: "22g",
    fiber: "3g",
    sodium: "680mg",
    tips: [
      "Use ripe, in-season tomatoes for best flavor",
      "Buffalo mozzarella is traditional but harder to slice",
      "Toast bread lightly - not too crispy",
      "Add prosciutto or salami for a heartier sandwich",
    ],
    ingredients: [
      "1 ciabatta bread",
      "200g fresh mozzarella, sliced",
      "2 large tomatoes, sliced",
      "Fresh basil leaves",
      "3 tablespoons pesto",
      "2 tablespoons balsamic glaze",
      "Olive oil",
      "Salt and pepper",
    ],
    instructions: [
      "Slice ciabatta bread in half horizontally.",
      "Toast bread lightly until just crispy",
      "Spread pesto on both sides of bread.",
      "Layer mozzarella slices, tomato slices, and fresh basil leaves.",
      "Drizzle with olive oil and balsamic glaze. Season with salt and pepper.",
      "Close sandwich, cut in half, and serve immediately.",
    ],
  },
  {
    recipesName: "BBQ Pulled Pork",
    recipesImg: "BBQ Pulled Pork.avif",
    disc: "Slow-cooked pulled pork coated in smoky barbecue sauce.",
    prepTime: "20 min",
    cookTime: "6 hrs",
    servings: "6 people",
    stars: "4.8",
    reviews: "(421 reviews)",
    tag1: "BBQ",
    tag2: "American",
    calories: "610 kcal",
    protein: "38g",
    carbohydrates: "40g",
    fat: "31g",
    fiber: "2g",
    sodium: "820mg",
    tips: [
      "Cook on low for the juiciest pork.",
      "Shred while still warm.",
      "Mix the meat with extra barbecue sauce before serving.",
      "Serve with coleslaw for extra crunch.",
    ],
    ingredients: [
      "1.5kg pork shoulder",
      "2 cups barbecue sauce",
      "2 teaspoons smoked paprika",
      "1 teaspoon garlic powder",
      "Salt and pepper",
      "Burger buns",
      "Coleslaw",
      "Pickles",
    ],
    instructions: [
      "Season pork with spices.",
      "Cook slowly until tender.",
      "Shred using two forks.",
      "Mix with barbecue sauce.",
      "Toast burger buns.",
      "Serve with coleslaw and pickles.",
    ],
  },

  {
    recipesName: "Beef Tacos",
    recipesImg: "Beef Tacos.avif",
    disc: "Mexican-style tacos filled with seasoned beef and fresh toppings.",
    prepTime: "15 min",
    cookTime: "15 min",
    servings: "4 people",
    stars: "4.7",
    reviews: "(356 reviews)",
    tag1: "Mexican",
    tag2: "Easy",
    calories: "520 kcal",
    protein: "29g",
    carbohydrates: "35g",
    fat: "28g",
    fiber: "6g",
    sodium: "710mg",
    tips: [
      "Warm tortillas before serving.",
      "Use fresh lime juice.",
      "Don't overfill the tacos.",
      "Top with cilantro.",
    ],
    ingredients: [
      "8 taco shells",
      "500g ground beef",
      "1 onion",
      "2 tomatoes",
      "Lettuce",
      "Cheddar cheese",
      "Taco seasoning",
      "Sour cream",
    ],
    instructions: [
      "Cook onion until soft.",
      "Brown the beef.",
      "Add taco seasoning.",
      "Warm taco shells.",
      "Fill shells with beef.",
      "Top with vegetables, cheese and sour cream.",
    ],
  },

  {
    recipesName: "Caesar Salad",
    recipesImg: "Caesar Salad.avif",
    disc: "Classic Caesar salad with crispy croutons and Parmesan cheese.",
    prepTime: "15 min",
    cookTime: "5 min",
    servings: "2 people",
    stars: "4.6",
    reviews: "(210 reviews)",
    tag1: "Healthy",
    tag2: "Salad",
    calories: "350 kcal",
    protein: "18g",
    carbohydrates: "20g",
    fat: "22g",
    fiber: "4g",
    sodium: "540mg",
    tips: [
      "Use chilled lettuce.",
      "Make fresh croutons.",
      "Add grilled chicken for extra protein.",
      "Serve immediately.",
    ],
    ingredients: [
      "Romaine lettuce",
      "Parmesan cheese",
      "Croutons",
      "Caesar dressing",
      "Chicken breast",
      "Olive oil",
      "Black pepper",
      "Lemon juice",
    ],
    instructions: [
      "Grill the chicken.",
      "Chop lettuce.",
      "Prepare dressing.",
      "Mix lettuce with dressing.",
      "Top with chicken, Parmesan and croutons.",
      "Serve immediately.",
    ],
  },

  {
    recipesName: "Chicken Stir-Fry",
    recipesImg: "Chicken Stir-Fry.avif",
    disc: "Quick stir-fried chicken with colorful vegetables and soy sauce.",
    prepTime: "15 min",
    cookTime: "15 min",
    servings: "4 people",
    stars: "4.8",
    reviews: "(301 reviews)",
    tag1: "Healthy",
    tag2: "Asian",
    calories: "460 kcal",
    protein: "35g",
    carbohydrates: "28g",
    fat: "20g",
    fiber: "5g",
    sodium: "640mg",
    tips: [
      "Cook over high heat.",
      "Don't overcrowd the pan.",
      "Prepare vegetables first.",
      "Serve immediately over rice.",
    ],
    ingredients: [
      "500g chicken breast",
      "Broccoli",
      "Bell peppers",
      "Carrots",
      "Soy sauce",
      "Garlic",
      "Ginger",
      "Sesame oil",
    ],
    instructions: [
      "Slice chicken.",
      "Cook chicken until golden.",
      "Add vegetables.",
      "Pour soy sauce mixture.",
      "Cook until vegetables are crisp.",
      "Serve with rice.",
    ],
  },

  {
    recipesName: "Chicken Tikka Masala",
    recipesImg: "Chicken Tikka Masala.avif",
    disc: "Tender chicken cooked in a rich and creamy tomato curry sauce.",
    prepTime: "25 min",
    cookTime: "35 min",
    servings: "4 people",
    stars: "4.9",
    reviews: "(518 reviews)",
    tag1: "Indian",
    tag2: "Spicy",
    calories: "590 kcal",
    protein: "37g",
    carbohydrates: "22g",
    fat: "36g",
    fiber: "4g",
    sodium: "760mg",
    tips: [
      "Marinate chicken overnight.",
      "Use Greek yogurt.",
      "Simmer sauce slowly.",
      "Serve with basmati rice.",
    ],
    ingredients: [
      "Chicken breast",
      "Greek yogurt",
      "Tomato puree",
      "Heavy cream",
      "Garam masala",
      "Garlic",
      "Ginger",
      "Butter",
    ],
    instructions: [
      "Marinate chicken.",
      "Grill until lightly charred.",
      "Prepare tomato sauce.",
      "Add cream and spices.",
      "Combine chicken with sauce.",
      "Serve with rice or naan.",
    ],
  },
  {
    recipesName: "Classic Beef Burger",
    recipesImg: "Classic Beef Burger.avif",
    disc: "Juicy grilled beef burger topped with cheese, lettuce, tomato and pickles.",
    prepTime: "15 min",
    cookTime: "15 min",
    servings: "2 people",
    stars: "4.8",
    reviews: "(542 reviews)",
    tag1: "American",
    tag2: "Burger",
    calories: "720 kcal",
    protein: "38g",
    carbohydrates: "42g",
    fat: "45g",
    fiber: "3g",
    sodium: "980mg",
    tips: [
      "Don't press the burger while cooking.",
      "Toast the buns lightly.",
      "Use 80/20 ground beef for juicy patties.",
      "Let the burger rest for 2 minutes.",
    ],
    ingredients: [
      "2 burger buns",
      "2 beef patties",
      "2 cheddar cheese slices",
      "Lettuce",
      "Tomato slices",
      "Pickles",
      "Ketchup",
      "Mayonnaise",
    ],
    instructions: [
      "Season beef patties.",
      "Grill for 4-5 minutes per side.",
      "Add cheese during the final minute.",
      "Toast burger buns.",
      "Assemble with vegetables and sauces.",
      "Serve immediately.",
    ],
  },

  {
    recipesName: "Creamy Spaghetti Carbonara",
    recipesImg: "Creamy Spaghetti Carbonara.avif",
    disc: "Classic Italian pasta tossed with bacon, Parmesan and creamy sauce.",
    prepTime: "10 min",
    cookTime: "20 min",
    servings: "4 people",
    stars: "4.9",
    reviews: "(466 reviews)",
    tag1: "Italian",
    tag2: "Pasta",
    calories: "640 kcal",
    protein: "24g",
    carbohydrates: "58g",
    fat: "35g",
    fiber: "3g",
    sodium: "730mg",
    tips: [
      "Reserve pasta water.",
      "Mix eggs off the heat.",
      "Use freshly grated Parmesan.",
      "Serve immediately.",
    ],
    ingredients: [
      "400g spaghetti",
      "200g bacon",
      "2 eggs",
      "Parmesan cheese",
      "Black pepper",
      "Garlic",
      "Butter",
      "Salt",
    ],
    instructions: [
      "Cook spaghetti.",
      "Cook bacon until crispy.",
      "Whisk eggs and Parmesan.",
      "Combine pasta and bacon.",
      "Mix in egg mixture.",
      "Serve with extra Parmesan.",
    ],
  },

  {
    recipesName: "French Onion Soup",
    recipesImg: "French Onion Soup.avif",
    disc: "Rich onion soup topped with toasted bread and melted cheese.",
    prepTime: "20 min",
    cookTime: "50 min",
    servings: "4 people",
    stars: "4.7",
    reviews: "(287 reviews)",
    tag1: "Soup",
    tag2: "French",
    calories: "390 kcal",
    protein: "15g",
    carbohydrates: "34g",
    fat: "18g",
    fiber: "4g",
    sodium: "860mg",
    tips: [
      "Caramelize onions slowly.",
      "Use beef stock.",
      "Toast bread first.",
      "Broil until cheese bubbles.",
    ],
    ingredients: [
      "4 onions",
      "Beef broth",
      "Butter",
      "French bread",
      "Gruyere cheese",
      "Garlic",
      "Thyme",
      "Black pepper",
    ],
    instructions: [
      "Slice onions.",
      "Cook until caramelized.",
      "Add broth and simmer.",
      "Toast bread.",
      "Top soup with bread and cheese.",
      "Broil until golden.",
    ],
  },

  {
    recipesName: "Greek Moussaka",
    recipesImg: "Greek Moussaka.avif",
    disc: "Layers of eggplant, seasoned beef and creamy béchamel sauce.",
    prepTime: "35 min",
    cookTime: "55 min",
    servings: "6 people",
    stars: "4.8",
    reviews: "(315 reviews)",
    tag1: "Greek",
    tag2: "Baked",
    calories: "610 kcal",
    protein: "32g",
    carbohydrates: "26g",
    fat: "38g",
    fiber: "6g",
    sodium: "690mg",
    tips: [
      "Salt eggplant before cooking.",
      "Let cool before slicing.",
      "Use fresh nutmeg.",
      "Bake until golden.",
    ],
    ingredients: [
      "Eggplants",
      "Ground beef",
      "Tomato sauce",
      "Onion",
      "Milk",
      "Butter",
      "Flour",
      "Parmesan",
    ],
    instructions: [
      "Cook eggplant slices.",
      "Prepare meat sauce.",
      "Make béchamel.",
      "Layer ingredients.",
      "Bake until golden.",
      "Rest before serving.",
    ],
  },

  {
    recipesName: "Honey Garlic Salmon",
    recipesImg: "Honey Garlic Salmon.avif",
    disc: "Pan-seared salmon glazed with sweet honey garlic sauce.",
    prepTime: "10 min",
    cookTime: "15 min",
    servings: "2 people",
    stars: "4.9",
    reviews: "(392 reviews)",
    tag1: "Seafood",
    tag2: "Healthy",
    calories: "520 kcal",
    protein: "36g",
    carbohydrates: "18g",
    fat: "28g",
    fiber: "1g",
    sodium: "620mg",
    tips: [
      "Pat salmon dry.",
      "Don't overcook.",
      "Use fresh garlic.",
      "Serve with rice.",
    ],
    ingredients: [
      "2 salmon fillets",
      "Honey",
      "Garlic",
      "Soy sauce",
      "Butter",
      "Lemon juice",
      "Parsley",
      "Black pepper",
    ],
    instructions: [
      "Season salmon.",
      "Sear skin-side down.",
      "Prepare honey garlic sauce.",
      "Coat salmon with sauce.",
      "Cook until flaky.",
      "Serve immediately.",
    ],
  },
  {
    recipesName: "Lasagna Bolognese",
    recipesImg: "Lasagna Bolognese.avif",
    disc: "Classic Italian lasagna layered with rich beef Bolognese and creamy béchamel.",
    prepTime: "30 min",
    cookTime: "1 hr",
    servings: "6 people",
    stars: "4.9",
    reviews: "(603 reviews)",
    tag1: "Italian",
    tag2: "Pasta",
    calories: "690 kcal",
    protein: "36g",
    carbohydrates: "49g",
    fat: "38g",
    fiber: "4g",
    sodium: "840mg",
    tips: [
      "Let it rest before slicing.",
      "Use freshly grated mozzarella.",
      "Don't overcook the pasta sheets.",
      "Bake until golden brown.",
    ],
    ingredients: [
      "Lasagna sheets",
      "500g ground beef",
      "Tomato sauce",
      "Béchamel sauce",
      "Mozzarella cheese",
      "Parmesan cheese",
      "Onion",
      "Garlic",
    ],
    instructions: [
      "Prepare the meat sauce.",
      "Make the béchamel sauce.",
      "Layer pasta, meat and béchamel.",
      "Repeat the layers.",
      "Top with cheese.",
      "Bake until golden.",
    ],
  },

  {
    recipesName: "Margherita Pizza",
    recipesImg: "Margherita Pizza.avif",
    disc: "Traditional pizza topped with tomato sauce, mozzarella and fresh basil.",
    prepTime: "20 min",
    cookTime: "15 min",
    servings: "4 people",
    stars: "4.8",
    reviews: "(489 reviews)",
    tag1: "Italian",
    tag2: "Pizza",
    calories: "560 kcal",
    protein: "21g",
    carbohydrates: "58g",
    fat: "24g",
    fiber: "3g",
    sodium: "760mg",
    tips: [
      "Use fresh mozzarella.",
      "Bake in a very hot oven.",
      "Add basil after baking.",
      "Use pizza stone if available.",
    ],
    ingredients: [
      "Pizza dough",
      "Tomato sauce",
      "Fresh mozzarella",
      "Fresh basil",
      "Olive oil",
      "Parmesan",
      "Salt",
      "Black pepper",
    ],
    instructions: [
      "Roll out the dough.",
      "Spread tomato sauce.",
      "Add mozzarella.",
      "Bake until crust is crisp.",
      "Top with basil.",
      "Drizzle olive oil before serving.",
    ],
  },

  {
    recipesName: "Mediterranean Quinoa Bowl",
    recipesImg: "Mediterranean Quinoa Bowl.avif",
    disc: "Healthy quinoa bowl loaded with fresh vegetables and feta cheese.",
    prepTime: "15 min",
    cookTime: "20 min",
    servings: "2 people",
    stars: "4.7",
    reviews: "(244 reviews)",
    tag1: "Healthy",
    tag2: "Mediterranean",
    calories: "470 kcal",
    protein: "19g",
    carbohydrates: "48g",
    fat: "18g",
    fiber: "8g",
    sodium: "520mg",
    tips: [
      "Cook quinoa in vegetable broth.",
      "Use fresh vegetables.",
      "Serve chilled or warm.",
      "Add grilled chicken if desired.",
    ],
    ingredients: [
      "Quinoa",
      "Cherry tomatoes",
      "Cucumber",
      "Feta cheese",
      "Olives",
      "Red onion",
      "Olive oil",
      "Lemon juice",
    ],
    instructions: [
      "Cook quinoa.",
      "Chop vegetables.",
      "Mix vegetables with quinoa.",
      "Add feta and olives.",
      "Dress with olive oil and lemon.",
      "Serve immediately.",
    ],
  },

  {
    recipesName: "Pad Thai",
    recipesImg: "Pad Thai.avif",
    disc: "Traditional Thai rice noodles stir-fried with shrimp, peanuts and tamarind sauce.",
    prepTime: "20 min",
    cookTime: "15 min",
    servings: "4 people",
    stars: "4.8",
    reviews: "(377 reviews)",
    tag1: "Thai",
    tag2: "Noodles",
    calories: "590 kcal",
    protein: "28g",
    carbohydrates: "61g",
    fat: "24g",
    fiber: "4g",
    sodium: "910mg",
    tips: [
      "Soak noodles before cooking.",
      "Cook on high heat.",
      "Don't overcook the shrimp.",
      "Top with crushed peanuts.",
    ],
    ingredients: [
      "Rice noodles",
      "Shrimp",
      "Eggs",
      "Bean sprouts",
      "Green onions",
      "Peanuts",
      "Tamarind sauce",
      "Lime",
    ],
    instructions: [
      "Soak noodles.",
      "Cook shrimp.",
      "Scramble eggs.",
      "Add noodles and sauce.",
      "Mix in vegetables.",
      "Serve with peanuts and lime.",
    ],
  },

  {
    recipesName: "Shrimp Scampi",
    recipesImg: "Shrimp Scampi.avif",
    disc: "Juicy shrimp cooked in garlic butter and lemon sauce.",
    prepTime: "10 min",
    cookTime: "15 min",
    servings: "2 people",
    stars: "4.8",
    reviews: "(298 reviews)",
    tag1: "Seafood",
    tag2: "Quick",
    calories: "430 kcal",
    protein: "34g",
    carbohydrates: "10g",
    fat: "28g",
    fiber: "1g",
    sodium: "650mg",
    tips: [
      "Use fresh shrimp.",
      "Don't overcook the shrimp.",
      "Finish with fresh parsley.",
      "Serve over pasta.",
    ],
    ingredients: [
      "Shrimp",
      "Butter",
      "Garlic",
      "Lemon juice",
      "Parsley",
      "Olive oil",
      "Salt",
      "Black pepper",
    ],
    instructions: [
      "Season shrimp.",
      "Cook shrimp in butter.",
      "Add garlic.",
      "Pour in lemon juice.",
      "Finish with parsley.",
      "Serve hot.",
    ],
  },
  {
    recipesName: "Teriyaki Chicken Bowl",
    recipesImg: "Teriyaki Chicken Bowl.avif",
    disc: "Tender teriyaki chicken served over fluffy rice with fresh vegetables.",
    prepTime: "15 min",
    cookTime: "20 min",
    servings: "4 people",
    stars: "4.9",
    reviews: "(435 reviews)",
    tag1: "Japanese",
    tag2: "Healthy",
    calories: "540 kcal",
    protein: "35g",
    carbohydrates: "46g",
    fat: "18g",
    fiber: "5g",
    sodium: "740mg",
    tips: [
      "Marinate the chicken for at least 30 minutes.",
      "Use freshly cooked rice.",
      "Don't overcook the vegetables.",
      "Sprinkle with sesame seeds before serving.",
    ],
    ingredients: [
      "2 chicken breasts",
      "2 cups cooked rice",
      "Broccoli florets",
      "Carrots, sliced",
      "Teriyaki sauce",
      "Sesame oil",
      "Green onions",
      "Sesame seeds",
    ],
    instructions: [
      "Cut chicken into bite-sized pieces.",
      "Cook chicken until golden.",
      "Pour in teriyaki sauce and simmer.",
      "Steam broccoli and carrots.",
      "Serve chicken over rice with vegetables.",
      "Garnish with green onions and sesame seeds.",
    ],
  },

  {
    recipesName: "Thai Green Curry",
    recipesImg: "Thai Green Curry.avif",
    disc: "Creamy Thai green curry with chicken, vegetables and fragrant herbs.",
    prepTime: "20 min",
    cookTime: "25 min",
    servings: "4 people",
    stars: "4.8",
    reviews: "(387 reviews)",
    tag1: "Thai",
    tag2: "Spicy",
    calories: "560 kcal",
    protein: "31g",
    carbohydrates: "24g",
    fat: "36g",
    fiber: "6g",
    sodium: "790mg",
    tips: [
      "Use full-fat coconut milk.",
      "Adjust the curry paste to your spice preference.",
      "Fresh basil enhances the flavor.",
      "Serve with jasmine rice.",
    ],
    ingredients: [
      "500g chicken breast",
      "Green curry paste",
      "Coconut milk",
      "Bell peppers",
      "Zucchini",
      "Thai basil",
      "Fish sauce",
      "Jasmine rice",
    ],
    instructions: [
      "Cook the curry paste in a little oil.",
      "Add coconut milk and stir.",
      "Cook the chicken until tender.",
      "Add vegetables.",
      "Simmer until vegetables are cooked.",
      "Serve over jasmine rice.",
    ],
  },

  {
    recipesName: "Vegetable Curry",
    recipesImg: "Vegetable Curry.avif",
    disc: "A hearty vegetable curry packed with colorful vegetables and aromatic spices.",
    prepTime: "15 min",
    cookTime: "30 min",
    servings: "4 people",
    stars: "4.7",
    reviews: "(264 reviews)",
    tag1: "Vegetarian",
    tag2: "Healthy",
    calories: "420 kcal",
    protein: "12g",
    carbohydrates: "45g",
    fat: "18g",
    fiber: "10g",
    sodium: "590mg",
    tips: [
      "Use seasonal vegetables.",
      "Don't overcook the vegetables.",
      "Add spinach at the end.",
      "Serve with naan or basmati rice.",
    ],
    ingredients: [
      "Potatoes",
      "Carrots",
      "Cauliflower",
      "Peas",
      "Coconut milk",
      "Curry powder",
      "Garlic",
      "Onion",
    ],
    instructions: [
      "Cook onion and garlic until soft.",
      "Add curry powder and stir.",
      "Add vegetables and coconut milk.",
      "Simmer until vegetables are tender.",
      "Season to taste.",
      "Serve with rice or naan.",
    ],
  },
];

window.onload = function () {
  generateRandom();
};

function generateRandom() {
  var randomIndex = Math.floor(Math.random() * recipes.length);
  var recipe = recipes[randomIndex];

  document.getElementById("rname").textContent = recipe.recipesName;
  document.getElementById("rde").textContent = recipe.disc;

  document.getElementById("recipe-img").src = "images/" + recipe.recipesImg;
  document.getElementById("recipe-img").alt = recipe.recipesName;

  document.getElementById("stars").textContent = recipe.stars;
  document.getElementById("reviews").textContent = recipe.reviews;

  document.getElementById("preptime").textContent = recipe.prepTime;
  document.getElementById("cooktime").textContent = recipe.cookTime;
  document.getElementById("servings").textContent = recipe.servings;

  document.getElementById("Tag1").textContent = recipe.tag1;
  document.getElementById("Tag2").textContent = recipe.tag2;

  document.getElementById("Calories").textContent = recipe.calories;
  document.getElementById("Protein").textContent = recipe.protein;
  document.getElementById("Carbohydrates").textContent = recipe.carbohydrates;
  document.getElementById("Fat").textContent = recipe.fat;
  document.getElementById("Fiber").textContent = recipe.fiber;
  document.getElementById("Sodium").textContent = recipe.sodium;

  var ingredientsBox = "";

  for (var i = 0; i < recipe.ingredients.length; i++) {
    ingredientsBox += `
    <li class="d-flex align-items-center mb-4">
      <span class="ingredient-number rounded-circle d-flex justify-content-center align-items-center me-3">
        ${i + 1}
      </span>

      <span class="fs-5">${recipe.ingredients[i]}</span>
    </li>
  `;
  }

  document.getElementById("ingredientsList").innerHTML = ingredientsBox;

  var instructionsBox = "";

  for (var i = 0; i < recipe.instructions.length; i++) {
    instructionsBox += `
    <div class="d-flex align-items-center mb-5">
      <div class="steps bg-main text-light fw-bold fs-4 d-flex justify-content-center align-items-center me-4">
        ${i + 1}
      </div>

      <p class="fs-6 mb-0">
        ${recipe.instructions[i]}
      </p>
    </div>
  `;
  }

  document.getElementById("instructionsList").innerHTML = instructionsBox;

  var tipsBox = "";

  for (var i = 0; i < recipe.tips.length; i++) {
    tipsBox += `
    <div class="d-flex tip-container p-2 mb-3">
      <div class="tip-icon rounded-circle text-center d-flex justify-content-center align-items-center me-2">
        <i class="fa-solid fa-check"></i>
      </div>

      <p class="mb-0">
        ${recipe.tips[i]}
      </p>
    </div>
  `;
  }

  document.getElementById("tipsList").innerHTML = tipsBox;
}
